services:
  template-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=:8080
      - USE_FILE_SYSTEM=false
      - USE_SQLITE=true
      - SQLITE_PATH=/app/data/template-service.db
      - DEBUG=true
    restart: unless-stopped
